import { Types } from "mongoose";

// Export raw user data without hashed passwords
export const users = [
  // College Admins
  {
    _id: new Types.ObjectId("650000000000000000000011"),
    name: "Ram Sharma",
    email: "ram@heraldcollege.edu.np",
    password: "Admin@123", // Plain password - will be hashed during seeding
    role: "college_admin",
    collegeId: new Types.ObjectId("650000000000000000000001"),
    avatar: "https://res.cloudinary.com/demo/image/upload/v1/users/ram.jpg",
    isActive: true,
    lastActive: new Date(),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },
  {
    _id: new Types.ObjectId("650000000000000000000012"),
    name: "Sita Adhikari",
    email: "sita@islington.edu.np",
    password: "Admin@123",
    role: "college_admin",
    collegeId: new Types.ObjectId("650000000000000000000002"),
    avatar: "https://res.cloudinary.com/demo/image/upload/v1/users/sita.jpg",
    isActive: true,
    lastActive: new Date(),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },
  {
    _id: new Types.ObjectId("650000000000000000000013"),
    name: "Hari Poudel",
    email: "hari@iic.edu.np",
    password: "Admin@123",
    role: "college_admin",
    collegeId: new Types.ObjectId("650000000000000000000003"),
    avatar: "https://res.cloudinary.com/demo/image/upload/v1/users/hari.jpg",
    isActive: true,
    lastActive: new Date(),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },

  // Students - Herald College
  {
    _id: new Types.ObjectId("650000000000000000000021"),
    name: "Bishal Thapa",
    email: "bishal.thapa@heraldcollege.edu.np",
    password: "Student@123",
    role: "student",
    collegeId: new Types.ObjectId("650000000000000000000001"),
    avatar: "https://res.cloudinary.com/demo/image/upload/v1/users/bishal.jpg",
    isActive: true,
    lastActive: new Date(),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },
  {
    _id: new Types.ObjectId("650000000000000000000022"),
    name: "Shristi Karki",
    email: "shristi.karki@heraldcollege.edu.np",
    password: "Student@123",
    role: "student",
    collegeId: new Types.ObjectId("650000000000000000000001"),
    avatar: "https://res.cloudinary.com/demo/image/upload/v1/users/shristi.jpg",
    isActive: true,
    lastActive: new Date(),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },
  {
    _id: new Types.ObjectId("650000000000000000000023"),
    name: "Aayush Gurung",
    email: "aayush.gurung@heraldcollege.edu.np",
    password: "Student@123",
    role: "student",
    collegeId: new Types.ObjectId("650000000000000000000001"),
    avatar: "https://res.cloudinary.com/demo/image/upload/v1/users/aayush.jpg",
    isActive: true,
    lastActive: new Date(),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },

  // Students - Islington College
  {
    _id: new Types.ObjectId("650000000000000000000024"),
    name: "Pragya Shrestha",
    email: "pragya@islington.edu.np",
    password: "Student@123",
    role: "student",
    collegeId: new Types.ObjectId("650000000000000000000002"),
    avatar: "https://res.cloudinary.com/demo/image/upload/v1/users/pragya.jpg",
    isActive: true,
    lastActive: new Date(),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },
  {
    _id: new Types.ObjectId("650000000000000000000025"),
    name: "Roshan KC",
    email: "roshan@islington.edu.np",
    password: "Student@123",
    role: "student",
    collegeId: new Types.ObjectId("650000000000000000000002"),
    avatar: "https://res.cloudinary.com/demo/image/upload/v1/users/roshan.jpg",
    isActive: true,
    lastActive: new Date(),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },

  // Students - IIC
  {
    _id: new Types.ObjectId("650000000000000000000026"),
    name: "Anjali Rai",
    email: "anjali@iic.edu.np",
    password: "Student@123",
    role: "student",
    collegeId: new Types.ObjectId("650000000000000000000003"),
    avatar: "https://res.cloudinary.com/demo/image/upload/v1/users/anjali.jpg",
    isActive: true,
    lastActive: new Date(),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },
  {
    _id: new Types.ObjectId("650000000000000000000027"),
    name: "Suman Bhattarai",
    email: "suman@iic.edu.np",
    password: "Student@123",
    role: "student",
    collegeId: new Types.ObjectId("650000000000000000000003"),
    avatar: "https://res.cloudinary.com/demo/image/upload/v1/users/suman.jpg",
    isActive: true,
    lastActive: new Date(),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },

  // Inactive user
  {
    _id: new Types.ObjectId("650000000000000000000028"),
    name: "Inactive User",
    email: "inactive@heraldcollege.edu.np",
    password: "Inactive@123",
    role: "student",
    collegeId: new Types.ObjectId("650000000000000000000001"),
    avatar: null,
    isActive: false,
    lastActive: new Date("2024-01-05"),
    chatPrivacy: {
      allowMessagesFrom: "everyone",
      showReadReceipts: true,
    },
    notificationPreferences: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      comments: true,
    },
  },
];
